type Team = {
  id: number;
  sport_id: number;
  country_id: number;
  venue_id: number;
  gender: string;
  name: string;
  short_code: string | null;
  image_path: string;
  founded: number;
  type: string;
  placeholder: boolean;
  last_played_at: string;
  website: string;
  background_color: string;
};

export const teams: Team[] = [
  {
    id: 1071,
    sport_id: 1,
    country_id: 404,
    venue_id: 417,
    gender: "male",
    name: "Kasımpaşa",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/15/1071.png",
    founded: 1921,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-09 10:30:00",
    website: "https://www.kasimpasa.com.tr",
    background_color: "bg-[#fefefe]/50",
  },
  {
    id: 2811,
    sport_id: 1,
    country_id: 404,
    venue_id: 148509,
    gender: "male",
    name: "Samsunspor",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/27/2811.png",
    founded: 1965,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-07 17:00:00",
    website: "https://www.samsunspor.org.tr",
    background_color: "bg-[#d3d3d3]/50",
  },
  {
    id: 4192,
    sport_id: 1,
    country_id: 404,
    venue_id: 72011,
    gender: "male",
    name: "Gaziantep F.K.",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/0/4192.png",
    founded: 1988,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-06 17:45:00",
    website: "https://www.gaziantepfk.org",
    background_color: "bg-[#b99081]/50",
  },
  {
    id: 1041,
    sport_id: 1,
    country_id: 404,
    venue_id: 171292,
    gender: "male",
    name: "Rizespor",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/17/1041.png",
    founded: 1953,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-09 10:30:00",
    website: "https://www.caykurrizespor.org.tr",
    background_color: "bg-[#2f3a53]/50",
  },
  {
    id: 81,
    sport_id: 1,
    country_id: 404,
    venue_id: 71984,
    gender: "male",
    name: "Antalyaspor",
    short_code: "ANT",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/17/81.png",
    founded: 1966,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-09 16:00:00",
    website: "https://www.antalyaspor.com.tr",
    background_color: "bg-[#da6e22]/50",
  },
  {
    id: 347,
    sport_id: 1,
    country_id: 404,
    venue_id: 72107,
    gender: "male",
    name: "Alanyaspor",
    short_code: "ANY",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/27/347.png",
    founded: 1948,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-09 13:00:00",
    website: "https://www.alanyaspor.org.tr",
    background_color: "bg-[#c5c5c6]/50",
  },
  {
    id: 3224,
    sport_id: 1,
    country_id: 404,
    venue_id: 1886,
    gender: "male",
    name: "Eyüpspor",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/24/3224.png",
    founded: 1919,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-04 15:00:00",
    website: "https://www.eyupspor.org.tr",
    background_color: "bg-[#ec898b]/50",
  },
  {
    id: 3897,
    sport_id: 1,
    country_id: 404,
    venue_id: 2284,
    gender: "male",
    name: "Göztepe",
    short_code: "GOZ",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/25/3897.png",
    founded: 1925,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-06 17:45:00",
    website: "https://www.goztepe.org.tr",
    background_color: "bg-[#f2efef]/50",
  },
  {
    id: 88,
    sport_id: 1,
    country_id: 404,
    venue_id: 9695,
    gender: "male",
    name: "Fenerbahçe",
    short_code: "FEN",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/24/88.png",
    founded: 1907,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-09 13:00:00",
    website: "https://www.fenerbahce.org",
    background_color: "bg-[#e6dc6d] text-black",
  },
  {
    id: 13924,
    sport_id: 1,
    country_id: 404,
    venue_id: 9690,
    gender: "male",
    name: "Bodrumspor",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/4/13924.png",
    founded: 1931,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-05 12:30:00",
    website: "https://www.bodrumspor.com.tr",
    background_color: "bg-[#5e5d67]/50",
  },
  {
    id: 34,
    sport_id: 1,
    country_id: 404,
    venue_id: 9667,
    gender: "male",
    name: "Galatasaray",
    short_code: "GAL",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/2/34.png",
    founded: 1905,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-06 13:00:00",
    website: "https://www.galatasaray.org",
    background_color: "bg-[#dedfdf]/50",
  },
  {
    id: 365,
    sport_id: 1,
    country_id: 404,
    venue_id: 73015,
    gender: "male",
    name: "Sivasspor",
    short_code: "SIV",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/13/365.png",
    founded: 1967,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-08 16:00:00",
    website: "https://www.sivasspor.org.tr",
    background_color: "bg-[#9a794d]/50",
  },
  {
    id: 688,
    sport_id: 1,
    country_id: 404,
    venue_id: 214665,
    gender: "male",
    name: "Trabzonspor",
    short_code: "TRA",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/16/688.png",
    founded: 1967,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-05 10:00:00",
    website: "https://www.trabzonspor.org.tr",
    background_color: "bg-[#a10829]/90 text-white",
  },
  {
    id: 1039,
    sport_id: 1,
    country_id: 404,
    venue_id: 400,
    gender: "male",
    name: "Adana Demirspor",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/15/1039.png",
    founded: 1941,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-02 10:30:00",
    website: "https://www.adanademirspor.org.tr",
    background_color: "bg-[#e4aeac]/50",
  },
  {
    id: 554,
    sport_id: 1,
    country_id: 404,
    venue_id: 340175,
    gender: "male",
    name: "Beşiktaş",
    short_code: "BES",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/10/554.png",
    founded: 1903,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-08 16:00:00",
    website: "https://www.bjk.com.tr",
    background_color: "bg-[#95352c]/50",
  },
  {
    id: 13833,
    sport_id: 1,
    country_id: 404,
    venue_id: 9614,
    gender: "male",
    name: "Hatayspor",
    short_code: null,
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/9/13833.png",
    founded: 1967,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-07 17:00:00",
    website: "https://www.hatayspor.org.tr",
    background_color: "bg-[#f6d4cd]/50",
  },
  {
    id: 643,
    sport_id: 1,
    country_id: 404,
    venue_id: 161,
    gender: "male",
    name: "Kayserispor",
    short_code: "KAY",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/3/643.png",
    founded: 1966,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-08 16:00:00",
    website: "https://www.kayserispor.org.tr",
    background_color: "bg-[#9ea1a3]/50",
  },
  {
    id: 3702,
    sport_id: 1,
    country_id: 404,
    venue_id: 2168,
    gender: "male",
    name: "İstanbul Başakşehir",
    short_code: "IBA",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/22/3702.png",
    founded: 1990,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-09 16:00:00",
    website: "https://www.ibasaksehir.com.tr",
    background_color: "bg-[#b4b5b5]/50",
  },
  {
    id: 2632,
    sport_id: 1,
    country_id: 404,
    venue_id: 71803,
    gender: "male",
    name: "Konyaspor",
    short_code: "KON",
    image_path: "https://cdn.sportmonks.com/images/soccer/teams/8/2632.png",
    founded: 1981,
    type: "domestic",
    placeholder: false,
    last_played_at: "2025-02-08 13:00:00",
    website: "https://www.konyaspor.org.tr",
    background_color: "bg-[#8a7683]/50",
  },
];
